[package]
name = "rustling-data"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio-native-tls", "macros"] }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
futures = "0.3.31"
mongodb = "3.3.0"

[dev-dependencies]
sync_postgres = { package = "postgres", version = "0.19" }

# Your testcontainers dependency remains the same
testcontainers-modules = { version = "0.7", features = ["postgres", "blocking"] }