[package]
name = "rustling-derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
rustling-api = { path = "../rustling-api" }
rustling-core = { path = "../rustling-core" }
heck = "0.5.0"